// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsahwqkuojwfeiusyfib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzYWh3cWt1b2p3ZmVpdXN5ZmliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MjY2MjMsImV4cCI6MjA1NzIwMjYyM30.4NRrWYshF6FJl57xprg2fFPiYXBmXFl0ial0Iah7tzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);